// File generated by flutterfire configure
// WARNING: Once you have used this file, be careful about moving it around.
// Ensure that you keep it in the Flutter project root directory at all times.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoWebKeyRaktaSetu',
    appId: '1:123456789:web:demowebappraktasetu',
    messagingSenderId: '123456789',
    projectId: 'raktasetu-app',
    authDomain: 'raktasetu-app.firebaseapp.com',
    databaseURL: 'https://raktasetu-app.firebaseio.com',
    storageBucket: 'raktasetu-app.appspot.com',
    measurementId: 'G-DEMOWEBMEASUREMENT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoAndroidKeyRaktaSetu',
    appId: '1:123456789:android:demoandroidapprraktasetu',
    messagingSenderId: '123456789',
    projectId: 'raktasetu-app',
    databaseURL: 'https://raktasetu-app.firebaseio.com',
    storageBucket: 'raktasetu-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDempiOSKeyRaktaSetu',
    appId: '1:123456789:ios:demoiosapprraktasetu',
    messagingSenderId: '123456789',
    projectId: 'raktasetu-app',
    databaseURL: 'https://raktasetu-app.firebaseio.com',
    storageBucket: 'raktasetu-app.appspot.com',
    iosBundleId: 'com.vquint.raktasetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoMacOSKeyRaktaSetu',
    appId: '1:123456789:macos:demomacosapprraktasetu',
    messagingSenderId: '123456789',
    projectId: 'raktasetu-app',
    databaseURL: 'https://raktasetu-app.firebaseio.com',
    storageBucket: 'raktasetu-app.appspot.com',
    iosBundleId: 'com.vquint.raktasetu',
  );
}
