// =====================================================================
// RAKTASETU APP - COMPLETE IMPLEMENTATION GUIDE
// =====================================================================

/*
STEP 1: Setup Dependencies
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. Run: flutter pub get

2. iOS Setup:
   - cd ios
   - pod install
   - cd ..

3. Android Setup:
   - Update android/app/build.gradle if needed for compileSdkVersion
   
4. Configure Firebase (Critical):
   https://firebase.google.com/docs/flutter/setup
   
   - Download google-services.json (Android) → android/app/
   - Download GoogleService-Info.plist (iOS) → ios/Runner/


STEP 2: Update main.dart
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by Firebase CLI
import 'package:raktasetu/core/di/service_locator.dart';
import 'package:raktasetu/core/theme/app_theme.dart';
import 'package:raktasetu/presentation/bloc/donor_search_bloc.dart';
import 'package:raktasetu/presentation/pages/donor_search_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // Setup Service Locator (Dependency Injection)
  setupServiceLocator();
  
  runApp(const RaktaSetuApp());
}

class RaktaSetuApp extends StatelessWidget {
  const RaktaSetuApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'RaktaSetu - Blood Donation',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.light,
      home: BlocProvider(
        create: (context) => getIt<DonorSearchBloc>(),
        child: const DonorSearchPage(),
      ),
    );
  }
}
```


STEP 3: Firebase Firestore Schema
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Collection: "donors"
Document: {userId}

Example Document:
{
  "id": "user123",
  "fullName": "Rajesh Kumar",
  "phoneNumber": "+919876543210",
  "bloodGroup": {
    "group": "O+",
    "isPositive": true,
    "primaryAbo": "O"
  },
  "location": {
    "latitude": 12.9716,
    "longitude": 77.5946,
    "address": "123 Main St, Bengaluru",
    "district": "Bengaluru Urban",
    "accuracy": 10.5
  },
  "district": "Bengaluru Urban",
  "isVisibleInSearch": true,
  "lastDonationDate": "2024-01-15T10:30:00Z",
  "nextAvailableDate": "2024-04-15T10:30:00Z",
  "totalDonations": 5,
  "rating": 4.8,
  "avatar": "https://storage.googleapis.com/...",
  "createdAt": "2023-06-01T08:00:00Z",
  "updatedAt": "2024-01-15T10:30:00Z"
}

Firestore Indexes:
- bloodGroup.group + district + isVisibleInSearch
- district + isVisibleInSearch
- location + isVisibleInSearch


STEP 4: Implement Firebase Datasource
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In lib/data/datasources/donor_remote_datasource.dart:

class DonorRemoteDataSourceImpl implements DonorRemoteDataSource {
  final FirebaseFirestore firestore;
  
  DonorRemoteDataSourceImpl({required this.firestore});

  @override
  Future<List<DonorModel>> searchDonorsByDistrict({
    required String bloodGroup,
    required String district,
  }) async {
    try {
      final snapshot = await firestore
          .collection('donors')
          .where('bloodGroup.group', isEqualTo: bloodGroup)
          .where('district', isEqualTo: district)
          .where('isVisibleInSearch', isEqualTo: true)
          .get();

      return snapshot.docs
          .map((doc) => DonorModel.fromJson(doc.data()))
          .toList();
    } catch (e) {
      throw Exception('Failed to search donors: $e');
    }
  }

  @override
  Future<List<DonorModel>> getAllDonors() async {
    try {
      final snapshot = await firestore
          .collection('donors')
          .where('isVisibleInSearch', isEqualTo: true)
          .get();

      return snapshot.docs
          .map((doc) => DonorModel.fromJson(doc.data()))
          .toList();
    } catch (e) {
      throw Exception('Failed to fetch donors: $e');
    }
  }

  @override
  Future<DonorModel> getDonorById(String donorId) async {
    try {
      final doc = await firestore.collection('donors').doc(donorId).get();
      
      if (!doc.exists) {
        throw Exception('Donor not found');
      }
      
      return DonorModel.fromJson(doc.data()!);
    } catch (e) {
      throw Exception('Failed to fetch donor: $e');
    }
  }
}


STEP 5: Android Permissions
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

android/app/src/main/AndroidManifest.xml:

<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.INTERNET" />


STEP 6: iOS Permissions
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ios/Runner/Info.plist:

<key>NSLocationWhenInUseUsageDescription</key>
<string>RaktaSetu needs your location to find nearby blood donors.</string>

<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>RaktaSetu needs your location to find nearby blood donors.</string>


STEP 7: Building & Testing
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. Run emulator / connect device
2. flutter run
3. Test location permission grant
4. Test 10km proximity filtering


CORE FEATURES IMPLEMENTED:
✓ Clean Architecture (Domain/Data/Presentation)
✓ BLoC State Management
✓ Haversine Formula (10km proximity filter)
✓ Firebase Integration (Firestore)
✓ Location Services (GPS)
✓ Material 3 Design (#8B0000 Blood Red)
✓ All 31 Karnataka Districts
✓ All 8 Blood Groups
✓ Donor Search (by location, district, nearby)
✓ Advanced Filtering


TODO: NEXT FEATURES:
- Authentication (OTP via Firebase Auth)
- User Profile Completion
- Booking System
- Emergency SOS Broadcast
- Privacy Toggle (Go Invisible)
- Lottie Animations
- Google Maps Integration
- Donation History
- User Ratings & Reviews
- Notification System
*/
